
SELECT  YEAR(A.SALES_DATE) AS YEAR
,       MONTH(A.SALES_DATE) AS MONTH
,       B.GENDER
,       COUNT(DISTINCT A.USER_ID) AS USERS
FROM ONLINE_SALE A
INNER JOIN (   SELECT *
                    FROM USER_INFO
                    WHERE GENDER IS NOT NULL
            ) B ON B.USER_ID    =   A.USER_ID
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER