WITH TMP AS (SELECT  HOUR(DATETIME) AS HOUR
,       COUNT(DATETIME) AS COUNT
FROM ANIMAL_OUTS 
GROUP BY HOUR
ORDER BY HOUR
)

SELECT  IFNULL(MAX(HOUR),0) AS HOUR
,       IFNULL(COUNT,0) AS COUNT
FROM TMP
WHERE HOUR = 0
UNION ALL 
SELECT  IFNULL(MAX(HOUR),1) AS HOUR
,       IFNULL(COUNT,0) AS COUNT
FROM TMP
WHERE HOUR = 1
UNION ALL 
SELECT  IFNULL(MAX(HOUR),2) AS HOUR
,       IFNULL(COUNT,0) AS COUNT
FROM TMP
WHERE HOUR = 2
UNION ALL
SELECT  IFNULL(MAX(HOUR),3) AS HOUR
,       IFNULL(COUNT,0) AS COUNT
FROM TMP
WHERE HOUR = 3
UNION ALL 
SELECT  IFNULL(MAX(HOUR),4) AS HOUR
,       IFNULL(COUNT,0) AS COUNT
FROM TMP
WHERE HOUR = 4
UNION ALL 
SELECT  IFNULL(MAX(HOUR),5) AS HOUR
,       IFNULL(COUNT,0) AS COUNT
FROM TMP
WHERE HOUR = 5
UNION ALL 
SELECT  IFNULL(MAX(HOUR),6) AS HOUR
,       IFNULL(COUNT,0) AS COUNT
FROM TMP
WHERE HOUR = 6
UNION ALL 
SELECT  IFNULL(MAX(HOUR),7) AS HOUR
,       IFNULL(COUNT,0) AS COUNT
FROM TMP
WHERE HOUR = 7
UNION ALL 
SELECT  IFNULL(MAX(HOUR),8) AS HOUR
,       IFNULL(COUNT,0) AS COUNT
FROM TMP
WHERE HOUR = 8
UNION ALL 
SELECT  IFNULL(MAX(HOUR),9) AS HOUR
,       IFNULL(COUNT,0) AS COUNT
FROM TMP
WHERE HOUR = 9
UNION ALL 
SELECT  IFNULL(MAX(HOUR),10) AS HOUR
,       IFNULL(COUNT,0) AS COUNT
FROM TMP
WHERE HOUR = 10
UNION ALL 
SELECT  IFNULL(MAX(HOUR),11) AS HOUR
,       IFNULL(COUNT,0) AS COUNT
FROM TMP
WHERE HOUR = 11
UNION ALL 
SELECT  IFNULL(MAX(HOUR),12) AS HOUR
,       IFNULL(COUNT,0) AS COUNT
FROM TMP
WHERE HOUR = 12
UNION ALL 
SELECT  IFNULL(MAX(HOUR),13) AS HOUR
,       IFNULL(COUNT,0) AS COUNT
FROM TMP
WHERE HOUR = 13
UNION ALL 
SELECT  IFNULL(MAX(HOUR),14) AS HOUR
,       IFNULL(COUNT,0) AS COUNT
FROM TMP
WHERE HOUR = 14
UNION ALL 
SELECT  IFNULL(MAX(HOUR),15) AS HOUR
,       IFNULL(COUNT,0) AS COUNT
FROM TMP
WHERE HOUR = 15
UNION ALL 
SELECT  IFNULL(MAX(HOUR),16) AS HOUR
,       IFNULL(COUNT,0) AS COUNT
FROM TMP
WHERE HOUR = 16
UNION ALL 
SELECT  IFNULL(MAX(HOUR),17) AS HOUR
,       IFNULL(COUNT,0) AS COUNT
FROM TMP
WHERE HOUR = 17
UNION ALL 
SELECT  IFNULL(MAX(HOUR),18) AS HOUR
,       IFNULL(COUNT,0) AS COUNT
FROM TMP
WHERE HOUR = 18
UNION ALL 
SELECT  IFNULL(MAX(HOUR),19) AS HOUR
,       IFNULL(COUNT,0) AS COUNT
FROM TMP
WHERE HOUR = 19
UNION ALL 
SELECT  IFNULL(MAX(HOUR),20) AS HOUR
,       IFNULL(COUNT,0) AS COUNT
FROM TMP
WHERE HOUR = 20
UNION ALL 
SELECT  IFNULL(MAX(HOUR),21) AS HOUR
,       IFNULL(COUNT,0) AS COUNT
FROM TMP
WHERE HOUR = 21
UNION ALL 
SELECT  IFNULL(MAX(HOUR),22) AS HOUR
,       IFNULL(COUNT,0) AS COUNT
FROM TMP
WHERE HOUR = 22
UNION ALL 
SELECT  IFNULL(MAX(HOUR),23) AS HOUR
,       IFNULL(COUNT,0) AS COUNT
FROM TMP
WHERE HOUR = 23
