-- 코드를 입력하세요
SELECT *
FROM (
SELECT
CAR_ID,
ROUND(SUM(END_DATE-START_DATE + 1) / COUNT(CAR_ID),1)
AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
GROUP BY CAR_ID
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC
)A
WHERE A.AVERAGE_DURATION >= 7