SELECT  A.CATEGORY
,       A.PRICE
,       A.PRODUCT_NAME
FROM FOOD_PRODUCT A
INNER JOIN (
            SELECT  CATEGORY
            ,       MAX(PRICE) MAX_PRICE
            FROM FOOD_PRODUCT 
            GROUP BY CATEGORY
) B ON  B.CATEGORY  =   A.CATEGORY
    AND B.MAX_PRICE =   A.PRICE
WHERE A.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY A.PRICE DESC