SELECT  M.MEMBER_NAME
,       R.REVIEW_TEXT
,       DATE_FORMAT(R.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW R
JOIN MEMBER_PROFILE M ON M.MEMBER_ID = R.MEMBER_ID
WHERE R.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(*) = (
                        SELECT COUNT(REVIEW_TEXT) CNT
                        FROM REST_REVIEW
                        GROUP BY MEMBER_ID
                        ORDER BY CNT DESC
                        LIMIT 1
                      )
)
ORDER BY R.REVIEW_DATE , R.REVIEW_TEXT