SELECT  ROUTE
,       CONCAT(ROUND(SUM(D_BETWEEN_DIST), 1), 'km') AS TOTAL_DISTANCE
,       CONCAT(ROUND(AVG(D_BETWEEN_DIST), 2), 'km') AS AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
order by ROUND(SUM(D_BETWEEN_DIST), 1) DESC -- TOTAL_DISTANCE는 문자열이기 때문에 숫자로 정렬을 처리해야한다.