WITH RECURSIVE CTE(ID, GENERATION) AS (
    SELECT  E1.ID
    ,       1 AS GENERATION
    FROM ECOLI_DATA E1
    WHERE PARENT_ID IS NULL
    UNION ALL 
    SELECT  E2.ID
    ,       E1.GENERATION + 1
    FROM CTE E1
    INNER JOIN ECOLI_DATA E2
        ON E1.ID = E2.PARENT_ID
)
SELECT  COUNT(E1.ID) AS COUNT
,       GENERATION
FROM CTE E1
WHERE NOT EXISTS(
    SELECT 1
    FROM ECOLI_DATA E2
    WHERE E2.PARENT_ID = E1.ID
)
GROUP BY GENERATION
ORDER BY GENERATION
