WITH TEMP AS(
    SELECT  CASE WHEN MONTH  <= 3 THEN '1Q'
                 WHEN MONTH  <= 6 THEN '2Q'
                 WHEN MONTH  <= 9 THEN '3Q'
                 ELSE '4Q' END AS QUARTER
    FROM (
            SELECT  MONTH(DIFFERENTIATION_DATE) AS MONTH
            FROM ECOLI_DATA
        )TEMP
)
SELECT  QUARTER
,       COUNT(QUARTER) AS ECOLI_COUNT
FROM TEMP
GROUP BY QUARTER
ORDER BY QUARTER