SELECT  B.AUTHOR_ID
,       A.AUTHOR_NAME
,       B.CATEGORY
,       SUM(B.PRICE * BS.SALES) AS TOTAL_SALES
FROM BOOK B
JOIN BOOK_SALES BS ON BS.BOOK_ID = B.BOOK_ID
JOIN AUTHOR A ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE DATE_FORMAT(BS.SALES_DATE,'%Y-%m') = '2022-01'
GROUP BY B.AUTHOR_ID , B.CATEGORY
ORDER BY B.AUTHOR_ID , B.CATEGORY DESC