-- 코드를 입력하세요
SELECT
PRODUCT_CODE,
SUM(OS.SALES_AMOUNT * PD.PRICE) as SALES
FROM PRODUCT PD
JOIN OFFLINE_SALE OS ON OS.PRODUCT_ID = PD.PRODUCT_ID
GROUP BY PD.PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE
