WITH SKILL AS(
    SELECT CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
)
SELECT  D.ID
,       D.EMAIL
,       D.FIRST_NAME
,       D.LAST_NAME
FROM DEVELOPERS D
WHERE EXISTS(
    SELECT 1
    FROM SKILL S
    WHERE D.SKILL_CODE | S.CODE = D.SKILL_CODE
)
ORDER BY D.ID