
SELECT  A.HISTORY_ID
,       ROUND(A.DAILY_FEE * A.DAYS * (100 - COALESCE(B.DISCOUNT_RATE,0))/100)
        AS FEE
FROM(
        SELECT  A.HISTORY_ID
        ,       B.DAILY_FEE
        ,       B.CAR_TYPE
        ,       DATEDIFF(A.END_DATE,A.START_DATE)+1 DAYS
        ,       CASE WHEN DATEDIFF(A.END_DATE,A.START_DATE)+1 < 7 THEN 0
                     WHEN DATEDIFF(A.END_DATE,A.START_DATE)+1 < 30 THEN 7
                     WHEN DATEDIFF(A.END_DATE,A.START_DATE)+1 < 90 THEN 3
                     ELSE 9 END DISC
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
        INNER JOIN CAR_RENTAL_COMPANY_CAR B ON B.CAR_ID = A.CAR_ID
        WHERE B.CAR_TYPE = '트럭'
    )A
LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B 
            ON  B.CAR_TYPE = A.CAR_TYPE
            AND LEFT(B.DURATION_TYPE,1) = DISC
ORDER BY FEE DESC, A.HISTORY_ID DESC
