
SELECT  A.PRODUCT_ID
,       B.PRODUCT_NAME
,       SUM(A.AMOUNT * B.PRICE) AS TOTAL_SALES
FROM FOOD_ORDER A
INNER JOIN FOOD_PRODUCT B 
    ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE DATE_FORMAT(A.PRODUCE_DATE,'%Y-%m') = '2022-05'
GROUP BY A.PRODUCT_ID, B.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC , A.PRODUCT_ID