
SELECT  ITEM_ID
,       ITEM_NAME
,       RARITY
FROM ITEM_INFO I
WHERE EXISTS (
    SELECT  1
    FROM ITEM_TREE IT
    JOIN ITEM_INFO II
        ON II.ITEM_ID = IT.PARENT_ITEM_ID
    WHERE II.RARITY = 'RARE'
    AND I.ITEM_ID = IT.ITEM_ID
)
ORDER BY ITEM_ID DESC