SELECT  E1.ID
,       E1.GENOTYPE
,       E2.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA E1
INNER JOIN ECOLI_DATA E2
    ON  E1.PARENT_ID = E2.ID
    AND E1.GENOTYPE & E2.GENOTYPE = E2.GENOTYPE
ORDER BY E1.ID