SELECT  ID
,       EMAIL
,       FIRST_NAME
,       LAST_NAME
FROM DEVELOPERS D
WHERE EXISTS(
    SELECT 1
    FROM SKILLCODES
    WHERE NAME IN ('Python','C#')
    AND D.SKILL_CODE | CODE = D.SKILL_CODE
)
ORDER BY ID