WITH TEMP AS (
    SELECT  SIZE_OF_COLONY
    ,       MAX(SIZE_OF_COLONY) OVER(PARTITION BY YEAR(DIFFERENTIATION_DATE)) MAX_SIZE
    ,       YEAR(DIFFERENTIATION_DATE) YEAR
    ,       ID
    FROM ECOLI_DATA
)
SELECT  YEAR
,       MAX_SIZE - SIZE_OF_COLONY AS YEAR_DEV
,       ID
FROM TEMP
ORDER BY YEAR, YEAR_DEV