SELECT SUM(CNT) FISH_COUNT
FROM(
        SELECT  COUNT(FI.FISH_NAME) CNT
        FROM FISH_NAME_INFO FI
        JOIN FISH_INFO F
            ON F.FISH_TYPE = FI.FISH_TYPE
        WHERE FI.FISH_NAME IN ('BASS', 'SNAPPER')
        GROUP BY FI.FISH_NAME
) TEMP