WITH TEMP AS(
    SELECT  FISH_TYPE
    ,       MAX(LENGTH) LENGTH
    FROM FISH_INFO 
    GROUP BY FISH_TYPE
)
SELECT  FI.ID
,       FNI.FISH_NAME
,       FI.LENGTH
FROM FISH_INFO FI
INNER JOIN FISH_NAME_INFO  FNI
    ON FNI.FISH_TYPE = FI.FISH_TYPE
WHERE EXISTS(
    SELECT 1
    FROM TEMP T
    WHERE   T.FISH_TYPE = FI.FISH_TYPE
    AND     T.LENGTH    = FI.LENGTH
)
ORDER BY FI.ID