SELECT  HD.DEPT_ID
,       HD.DEPT_NAME_EN
,       ROUND(AVG(HE.SAL)) AS AVG_SAL
FROM HR_DEPARTMENT HD
INNER JOIN HR_EMPLOYEES HE
    ON HE.DEPT_ID = HD.DEPT_ID
GROUP BY HD.DEPT_ID , HD.DEPT_NAME_EN
ORDER BY AVG(HE.SAL) DESC