WITH TEMP AS(
    SELECT  AVG(COALESCE(LENGTH,10)) AVG_LEN
    ,       COUNT(FISH_TYPE) FISH_COUNT
    ,       MAX(COALESCE(LENGTH,10)) MAX_LENGTH
    ,       FISH_TYPE
    FROM FISH_INFO 
    GROUP BY FISH_TYPE
)
SELECT  FISH_COUNT
,       MAX_LENGTH
,       FISH_TYPE
FROM TEMP
WHERE AVG_LEN >= 33
ORDER BY FISH_TYPE