WITH TEMP AS(
    SELECT
            CASE WHEN EXISTS(SELECT 1 FROM SKILLCODES S WHERE S.CATEGORY = 'Front End' AND S.CODE | D.SKILL_CODE = D.SKILL_CODE)
                 AND  EXISTS(SELECT 1 FROM SKILLCODES S WHERE S.NAME = 'Python' AND S.CODE | D.SKILL_CODE = D.SKILL_CODE)
                 THEN 'A'
                 WHEN EXISTS(SELECT 1 FROM SKILLCODES S WHERE S.NAME = 'C#' AND S.CODE | D.SKILL_CODE = D.SKILL_CODE)
                 THEN 'B'
                 WHEN EXISTS(SELECT 1 FROM SKILLCODES S WHERE S.CATEGORY = 'Front End' AND S.CODE | D.SKILL_CODE = D.SKILL_CODE)
                 THEN 'C'
                 ELSE NULL END AS GRADE
    ,       D.ID
    ,       D.EMAIL
    FROM DEVELOPERS D 
)
SELECT *
FROM TEMP
WHERE GRADE IS NOT NULL
ORDER BY GRADE, ID
